project_id = "tduabimmskinuyqinfdg"

[functions.oracle-chat]
verify_jwt = false

[functions.oracle-voice]
verify_jwt = false

[functions.oracle-vision]
verify_jwt = false

[functions.generate-image]
verify_jwt = false
